name: Workflow Run

on: 
  workflow_run:
    workflows: ["Push & Pull"]
      types:
        - completed

env: 
  DEMO_PLAIN: plain-text
  DEMO_SECRET: ${{ secrets.DEMO_SECRET }}

jobs:
  test:
    if: ${{ github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo $DEMO_PLAIN
      - run: echo $DEMO_SECRET
        